name: Create PR from feature-creation to develop

on:
  push:
    branches:
      - 'feature/*'
      - 'defect/*'
    paths-ignore:
      - '.github/**'

permissions:
  pull-requests: write
  contents: write

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract the branch name
        id: extract_branch
        run: |
          echo "SOURCE_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        env:
          GITHUB_REF: ${{ github.ref }}

      - name: Check if PR exists
        id: check_pr
        run: |
          PR_COUNT=$(gh pr list --base develop --head ${{ env.SOURCE_BRANCH }} --state open --json number --jq 'length')
          echo "PR_COUNT=$PR_COUNT" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.PR_ACCESS_TOKEN }}

      - name: Create PR if none exists
        if: env.PR_COUNT == '0'
        run: |
          gh pr create --base develop --head ${{ env.SOURCE_BRANCH }} --title "Merge ${{ env.SOURCE_BRANCH }} into develop" --body "This PR merges the ${env.SOURCE_BRANCH} branch into develop."
        env:
          GH_TOKEN: ${{ secrets.PR_ACCESS_TOKEN }}